### ISSUE TITLE
Correct interpretation of surrogate pairs in json parsing

### ISSUE THREAD

**Issue by pineapplemachine** [pineapplemachine/mach.d#8]
Surrogate pairs encoded using the form `\u0000\u0000` are incorrectly interpreted by the json parser as two independent code points instead of one.

**Comment by UplinkCoder** [comment]
close it already.

**Comment by UplinkCoder** [comment]
still not closed.

**Comment by pineapplemachine** [comment]
This case is now handled correctly and a pertinent JSONTestSuite test no longer fails thanks to the improved surrogate pair handling in `mach.text.utf` and `mach.text.escape`.

Still TODO: The `Escaper` type should be able to handle writing code points as `\uXXXX\uXXXX` surrogate pairs when `\xXX` and `\UXXXXXXXX` are not available; it currently will just fail to write the string.
